name: Test Pipeline

on:
  push:
    branches:
      - "github-action"

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:  docker build -t image .
      - name: Unit Tests
        run:  docker run --rm image nose2 -s /comp0010/test
      - name: System Tests
        run:  docker run --rm image nose2 -s /comp0010/system_test